#!/bin/sh

# source xprofile
source ~/.config/X11/xprofile

# Xresources
res=$XDG_CONFIG_HOME/X11/Xresources
[ -f "$res" ] && xrdb -merge "$res"

# wallpaper
[ ! -f "$XDG_DATA_HOME/wallpaper" ] && wget https://nikotile.xyz/wallpaper -P "$XDG_DATA_HOME"
[ -f /usr/bin/xwallpaper ] && xwallpaper --focus $XDG_DATA_HOME/wallpaper

# Window manager
exec awesome
